# Generated by Django 4.0.1 on 2022-01-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('creator', models.CharField(max_length=20)),
                ('creatorId', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('ownerId', models.IntegerField()),
                ('roles', models.CharField(max_length=200)),
            ],
        ),
    ]
